image_width: 688
image_height: 700
camera_name: pg_12481138
camera_matrix:
  rows: 3
  cols: 3
  data: [3457.697150, 0.000000, 370.095068, 0.000000, 3461.063030, 319.956578, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.026527, -0.785451, -0.001562, 0.003643, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [3451.309814, 0.000000, 369.984952, 0.000000, 0.000000, 3455.615967, 319.271597, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
